### ISSUE TITLE
Client fails to reconnect when server stalls

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2328] opened 2019-07-18 13:43 UTC
@shyba aware of this one and has the log file. If the server locks up, the client doesn't try to reconnect to another server or back to the main server when it's back up.

**Comment by tzarebczan** [comment] 2019-07-24 00:03
This is fixed

**Comment by lyoshenka** [comment] 2022-06-10 15:30
duplicate of #3194

**Closed by lyoshenka** 2022-06-10 15:30 UTC
Labels: priority: blocker
