### ISSUE TITLE
Jeremy Discussion -  Configurable param for search via sdk

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-sdk#2023] opened 2019-04-10 21:09 UTC
Search goes through SDK. SDK forwards calls to lighthouse. The user can edit the lighthouse instance address. Default is https://lighthouse.lbry.com

**Comment by alyssaoc** [comment] 2019-04-11 14:17
@tiger5226 Can you expand this issue? What is the action here?

**Comment by tiger5226** [comment] 2019-04-14 15:29
The action is to make it such that search goes through the SDK. Currently, this goes from the app to lighthouse directly. The idea is that LBRY Inc is not the only provider of the search service. Someone could run their own search instance that users might want to use which depending on country would have different results filtered. The following needs to be considered:

- [ ] [Current search API](https://lbryio.github.io/lighthouse/#tag/Search-API) becomes version 1. 
- [ ] A search provider must have an api (`<provider>/version`) for search versions supported so we can tell the user app side whether the search provider supports their version of the SDK when they choose that provider. I will create this api for lighthouse. 
- [ ] SDK needs to offer a setting api/configuration for assigning a search provider app side. 
- [ ] SDK needs to implement the v1 search apis so the app can leverage them for searching capabilities.

Below is a screenshot of the current [apis](https://lbryio.github.io/lighthouse/#tag/Search-API):

<img width="1421" alt="Screen Shot 2019-04-14 at 11 24 00 AM" src="https://user-images.githubusercontent.com/3402064/56095159-f38a7e80-5ea7-11e9-88b6-4a60599f9dab.png">

**Comment by tzarebczan** [comment] 2019-07-24 01:28
Closing, duplicate of https://github.com/lbryio/lbry-sdk/issues/2118

**Closed by tzarebczan** 2019-07-24 01:28 UTC
