### ISSUE TITLE
Downloads not appearing in `file_list`

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#3428] opened 2021-09-17 15:00 UTC
`get` calls do not put the file into `file_list`, whereas `file_save` calls do.

Expected: both should put it in the list.

Might be related to blob cleanup.

**Comment by belikor** [comment] 2021-09-18 03:30
I'm not sure about this. I've been testing `get` a lot in the last few days with v0.102, and the downloaded streams are always put in the file list.

The only relevant change that I see is 87094fc83f, which made `save_file` be `False` by default in the configuration. This means `get` explicitly needs `--save_file=True` if the configuration is not changed.

As I see, `get` uses `FileManager.download_from_uri()` which does a lot of stuff but eventually calls `ManagedStream.save_file()`.

On the other hand `file_save` is basically a wrapper around `ManagedStream.save_file()`.

So, it seems both call the same method eventually, only `get` tries resolving the claim name first, updates the claim, handles the payment and other things; meanwhile `file_save` just recreates the file if the stream name is found.

**Comment by shyba** [comment] 2021-09-21 07:38
@jackrobison I tried locally both using the api and app, but wasn't able to reproduce it.
The app takes a little while to show it but that is mostly cache.

Is there another way to reproduce? Or maybe it was confusion caused by this caching behavior from app?

**Comment by shyba** [comment] 2021-09-28 16:24
closing as not reproducible, reopen if there is a way

**Closed by shyba** 2021-09-28 16:24 UTC
